Repository wecode-bootcamp-korea/13-grafolWEo-backend, pull requests merged in 2020-10, with the labels that each got.

#1 Feature/seunghojeong
  .gitignore
  grafolWEo/settings.py
  grafolWEo/urls.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201020_1808.py
  user/migrations/0003_user_short_introduce.py
  user/migrations/0004_auto_20201020_2113.py
  user/migrations/0005_auto_20201020_2119.py
  user/migrations/0006_auto_20201021_1508.py
  user/migrations/0007_auto_20201021_1728.py
  user/migrations/0008_auto_20201022_1458.py
  user/migrations/0009_auto_20201022_1509.py
  user/migrations/0010_auto_20201022_2045.py
  user/migrations/0011_auto_20201022_2059.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  work/__init__.py
  work/admin.py
  work/apps.py
  work/migrations/0001_initial.py
  work/migrations/0002_auto_20201022_1516.py
  work/migrations/0003_auto_20201022_2045.py
  work/migrations/0004_auto_20201022_2059.py
  work/migrations/__init__.py
  work/models.py
  work/tests.py
Labels: Status: 리뷰 요청

#2 [정승호] 회원가입/로그인 엔드포인트 (feature/user)
  user/urls.py
  user/views.py
  work/urls.py
  work/views.py
Labels: Status: Accepted

#3 [김성태] 작품 메인페이지 엔드포인트 (feature/works_main)
  grafolWEo/urls.py
  user/views.py
  work/models.py
  work/urls.py
  work/views.py
Labels: Status: 리뷰 요청

#4 [김성태] 배경화면 메인페이지 엔트포인트 (feature/wallpaper_main)
  grafolWEo/urls.py
  user/utils.py
  work/migrations/0005_auto_20201026_1555.py
  work/migrations/0006_auto_20201026_1636.py
  work/migrations/0007_auto_20201026_1842.py
  work/migrations/0008_auto_20201026_1853.py
  work/migrations/0009_auto_20201027_1943.py
  work/urls.py
  work/views.py
Labels: Status: 리뷰 요청

#5 [정승호] 작품 상세 페이지 엔드포인트(feature/work_detail)
  grafolWEo/urls.py
  user/utils.py
  user/views.py
  work/urls.py
  work/views.py
Labels: Status: 수정 요청
